# Generated by Django 3.1.4 on 2021-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_Name', max_length=32)),
                ('last_name', models.CharField(db_column='last_Name', max_length=32)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'buyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuySellTransaction',
            fields=[
                ('tsnc_id', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'buy_sell_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'owner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('no_of_bedrooms', models.DecimalField(decimal_places=0, max_digits=2)),
                ('size', models.DecimalField(decimal_places=0, max_digits=10)),
                ('type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=32)),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentTransaction',
            fields=[
                ('tsnc_id', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'rent_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tenant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_Name', max_length=32)),
                ('last_name', models.CharField(db_column='last_Name', max_length=32)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
